### ISSUE TITLE
Right click on transaction

### ISSUE THREAD

**Issue by tymat** [israelcoin/Isracoin#10]
Right clicking on the transaction in the transaction's tab shows "Show transaction on Israchain" which takes you to a non-existent domain http://israchain.info

![screen shot 2014-03-31 at 11 37 51 pm](https://cloud.githubusercontent.com/assets/849457/2575355/6f8ce8aa-b94f-11e3-9c0d-8365ba0eb28c.png)

**Comment by guysoft** [comment]
Fixed with #11
