### ISSUE TITLE
Upgrade to Bitcoin 1.9 codebase / dogecoin 1.7 codebase

### ISSUE THREAD

**Issue by guysoft** [israelcoin/Isracoin#14]
So Dogecoin are in the works to upgrade their old codebase to Bitcoin's new 1.9 sources.
These sources have thousands of new commit messages from over a year. We can't add them one by one, so we are following Dogecoin's strategy - add a new branch off Bitcoin's source and switch to that branch once we have a stable wallet.

For now, the Dogecoin beta tree has been pushed to here: https://github.com/israelcoin/Isracoin/tree/dogecoin-1.7-beta

**Comment by guysoft** [comment]
@negedzuregal 
FYI. The main commits that need to be added are the initial changes, and genesis block.

Initial commit:
https://github.com/israelcoin/Isracoin/commit/4dfdd43db3058cf30cb68a13780fdc56bbca47a4

Genesis block:
https://github.com/israelcoin/Isracoin/commit/ca79e0700958e4c3e5a59019725a3a08b72f0d1b

**Comment by alonmuroch** [comment]
Since dogecoin 1.7 is very different than dogecoin 1.6(base code for isracoin), we should follow the initial commits done by the dogecoin team when they converted BTC 0.9 to dogecoin 1.7.

From what i've seen, the first commit is (on dogecoin 1.7 dev beta branch):
SHA : 1bf5913
Comment : "Protocol chagnes for dogecoin 1.5"
date : 22.3.14

**Comment by guysoft** [comment]
Suggest you go ask them at: http://webchat.freenode.net/?channels=dogecoin-dev

Be patient on IRC :)

**Comment by alonmuroch** [comment]
:+1:

**Comment by alonmuroch** [comment]
Code base for isracoin 1.7 is pushed (only in alpha testing)
@guysoft if its ok by you, we should close this issue. For future issues relating to isracoin 1.7 i added a label

**Comment by guysoft** [comment]
Fine by me
