### ISSUE TITLE
isracoind -daemon issue

### ISSUE THREAD

**Issue by onecloudmanagement** [israelcoin/Isracoin#17]
I keep getting this between code tags when running the isracoind -daemon even thou the file has been created and has the items in it.

<code>
/home/cmilian/.isracoin/isracoin.conf
It is recommended you use the following random password:
rpcuser=isracoinrpc
rpcpassword=Hfdsxv2Y2maNyQ3nAJgBFcxq5EH6rc5XyZi6aUFJuBE
(you do not need to remember this password)
The username and password MUST NOT be the same.
If the file does not exist, create it with owner-readable-only file permissions.
It is also recommended to set alertnotify so you are notified of problems;
for example: alertnotify=echo %s | mail -s "Isracoin Alert" admin@foo.com

**Comment by alonmuroch** [comment]
you should provide rpcuser and rpcpassword to launch the daemon

**Comment by onecloudmanagement** [comment]
That's the problem, its has been provided. File was created and edited.

**Comment by leofidus** [comment]
are you using a sufficiently long password (preferably the one being suggested)?

**Comment by onecloudmanagement** [comment]
Yes I am, I am using the suggested one.

**Comment by alonmuroch** [comment]
It can be 
1) rpcpassword is empty
2) rpcpassword = rpcuser
3) rpcpassword is too weak
