### ISSUE TITLE
MPOS setup

### ISSUE THREAD

**Issue by onecloudmanagement** [israelcoin/Isracoin#18]
I am installing MPOS for Isracoin, is there a isracoin_scrypt ? I needed to git clone it to stratum-mining/externals/
anyone successfully used MPOS for Isracoin?
Thanks

**Comment by OmarxGx** [comment]
Hi,

The litecoin_scrypt already installs the necessary modules to mine Isracoin. Continue setting the MPOS pool as you would for Litecoin. Let me know if you have any other issues.

Omar

**Comment by onecloudmanagement** [comment]
Thanks!

  Carmelo Milián
  cmilian@BeeSprout.com / http://BeeSprout.com
