### ISSUE TITLE
Isracoin Wallet generates new wallet addresses 

### ISSUE THREAD

**Issue by onecloudmanagement** [israelcoin/Isracoin#19]
My Isracoin wallet has in more that one occasion created a new wallet address for itself. I have to go then ahead and change the stratum setting on my MPOS. Is this normal behavior?

Also, getting this issues on this commands...
cmilian@fastminer:~$ isracoind getbalance ""
52.00600000

but if i do isracoind getinfo i get this...with a different balance.

 "version" : 1060100,
    "protocolversion" : 70002,
    "walletversion" : 60000,
    "balance" : 2.00000000,
    "blocks" : 47695,
    "timeoffset" : -3,
    "connections" : 8,
    "proxy" : "",
    "difficulty" : 28.27784052,
    "testnet" : false,
    "keypoololdest" : 1398543435,
    "keypoolsize" : 101,
    "paytxfee" : 0.00000000,
    "errors" : ""
where are the other 50? I cant find the wallet.

Thanks for you help !

**Comment by onecloudmanagement** [comment]
this is what i mean... Where are the 

Current account address. It changed on its own.....
cmilian@fastminer:~/stratum-mining/conf$ isracoind getaccountaddress ""
iMHNcYAtHxTR4zoSBAC2w6J3tonXMzrSAG

Only 2 in balance......
cmilian@fastminer:~/stratum-mining/conf$ isracoind getinfo
{
    "version" : 1060100,
    "protocolversion" : 70002,
    "walletversion" : 60000,
    "balance" : 2.00000000,
    "blocks" : 47695,
    "timeoffset" : -3,
    "connections" : 8,
    "proxy" : "",
    "difficulty" : 28.27784052,
    "testnet" : false,
    "keypoololdest" : 1398543435,
    "keypoolsize" : 101,
    "paytxfee" : 0.00000000,
    "errors" : ""
}

running the get balance to that address shows balance 0......
cmilian@fastminer:~/stratum-mining/conf$ isracoind getbalance iMHNcYAtHxTR4zoSBAC2w6J3tonXMzrSAG
0.00000000
cmilian@fastminer:~/stratum-mining/conf$

getting balance without specifying wallet shows total of 52.003000 ......
without wallet address....
cmilian@fastminer:~/stratum-mining/conf$ isracoind getbalance ""
52.00600000

**Comment by israelcoin** [comment]
From the sound of it, I think perhaps there is another account in the same wallet.dat file. (which is normal behavior, or rather, a standard feature). So the question here is if the MPOS created another account there or something like that. Do you see all the coins when opening QT for example? (not sure if you're supposed or not, so just asking).

**Comment by OmarxGx** [comment]
If this is MPOS check under the Admin Tab and then under Wallet Info. It should list all of the wallet addresses and their respective balances. Make sure that you configured MPOS to use the correct address for the finding and paying of blocks.

**Comment by onecloudmanagement** [comment]
I am not sure, but i was able to see balance on wallet after Isracoind -rescan

**Comment by guysoft** [comment]
When you say 'wallet address' do you mean a receive address? Because when you send money, part of the bitcoin protocol demands generating new addresses, because the output address must be different from the input. 
If this is the case I am closing this issue.
