### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by magicode** [israelcoin/Isracoin#2]
kubuntu 13.04

```
Isracoin/src$ ./isracoind 
isracoind: main.cpp:2882: bool InitBlockIndex(): Assertion `block.hashMerkleRoot == uint256("0x")' failed.
Aborted (core dumped)
```

**Comment by israelcoin** [comment]
Thank you for the input.

The error is due to the genesis block not being included in the early release. It was released for the purpose of code review, rather than being run as a wallet client.

The genesis block will be released once the mining beings (pls look at our website for countdown).

**Comment by magicode** [comment]
?אי אפשר לעשות ארנק שמוגבל בזמן.
כאילו שחלק מהפרוטוקול של המטבע זה שהוא יתחיל בתאריך מסוים.
בדיוק כמו החסימה שנמצאת בפרוטוקל שכל דקה בלוק ולא יותר מזה.

**Comment by magicode** [comment]
תוריד מהאתר.
הקוד מקור פה זה רק להמחשה בלבד.

**Comment by magicode** [comment]
ראיתי שעכשיו עידכנו את זה.

**Comment by guysoft** [comment]
@magicode  Please comment in English, so non-Hebrew speakers could also participate.

**Comment by guysoft** [comment]
Fixed

**Comment by magicode** [comment]
@guysoft  בבקשה תשלח תגובות בעברית כדי שגם דוברי עברית יוכלו להשתתף.

אני חשבתי שזה מטבע ישראלי.
אולי טעיתי?

**Comment by guysoft** [comment]
@magicode If you would look at the bug tracker of any software, even ones which are Hebrew-only, you will see the convention is to track in English (for example https://github.com/hasadna/Open-Knesset , or any repo at https://github.com/hasadna). If tomorrow morning Isracoin finds a critical bug in the Bitcoin/Litecoin/Dogecoin codebase you want the open source community to have access to it.
Its a convention in software development to track bugs in an international language, just as the convention in scientific papers is to use English.

**Comment by magicode** [comment]
@guysoft  אני חושב שיש צדק בדברך וגם אני כותב באנגלית עד כמה שאני יכול בפרוייקטים שלי

אבל מה  אתה מציע לאחד כמוני שלא יודע אנגלית טוב. אני יודע להבין אבל לא לכתוב משפטים ארוכים.
1. לתרגם ב"תרגום של גוגל" ולהשים פה. 
   { לדעתי זה רעיון רע  כי בעברית לפחות דוברי עברית יבינו אותי ובאנגלית מתורגמת אף אחד לא יבין אותי }
2. לא להגיב בכלל ולא לדווח על באגים
   { ומה יקרה אם אני ימצא באג קריטי עדיף שיהיה בעברית מאשר בכלל לא }
3. להגיב בעברית

סתם אני חושב שטוב שאני כותב בעברית ככה אם יש איזה מפתחים או גרפיקאים שיכולים לתרום ולא יודעים אנגלית שלא יתביישו בזה.

מקסימום מי שלא מבין עברית יכול לתרגם בגוגל.
