### ISSUE TITLE
Wallet and bexplorer show diferent balances, My PC wallet says is updated.

### ISSUE THREAD

**Issue by onecloudmanagement** [israelcoin/Isracoin#21]
Hi Guys, My PC Wallet and bexplorer show diferent balances, My PC wallet says is updated.

http://bexplorer.israelcoin.org/address/XXXXXXXXXXXXXXXX
it shows:
Balance: 1566.82882452 ISR
 Transactions in: 15
 Received: 1634.40396424 ISR
 Transactions out: 2
 Sent: 67.57513972 ISR

My PC Waller shows....

![wallet](https://cloud.githubusercontent.com/assets/3895113/3086015/84bf21cc-e521-11e3-882b-e500ff7a3ed3.jpg)

**Comment by guysoft** [comment]
This is not a bug.
Taken from here:
Applies to any crypto currency, not only DRK
http://krauspe.eu/r/DRKCoin/comments/26aqu0/my_wallet_and_blockchain_explorer_showing/

"In the newest version of the client, if you have 100 coins and you send 10 to a second address, 10 are sent to the address you specify and 90 are sent to a another hidden address that is generated and stored in your wallet, this might explain some of the confusion. This occurs even without checking the "darksend" box - it makes it impossible to determine if you sent 90 or you sent 10. "
