### ISSUE TITLE
icons of dogecoin

### ISSUE THREAD

**Issue by magicode** [israelcoin/Isracoin#3]
https://github.com/israelcoin/Isracoin/tree/isracoin-1.6/src/qt/res/images

**Comment by israelcoin** [comment]
Thank you, 

We actually caught this today as well and it has already been fixed and will be updated alongside the genesis block update.

**Comment by guysoft** [comment]
We are missing icons for mac, see #5

**Comment by israelcoin** [comment]
Already fixed
