### ISSUE TITLE
Mac icns icon is still showing Dogecoin

### ISSUE THREAD

**Issue by guysoft** [israelcoin/Isracoin#5]
The Isracoin icon set for mac is missing, this is how it looks on mac:
![status1](https://cloud.githubusercontent.com/assets/325670/2535581/c8169e02-b590-11e3-88c8-c8e1623d6585.png)

File should be created, and renamed at https://github.com/israelcoin/Isracoin/tree/isracoin-1.6/src/mac/artwork

**Comment by tymat** [comment]
Bump

**Comment by guysoft** [comment]
![Damn it jim! I am an issue tracker, not a forum thread!](http://cdn.memegenerator.net/instances/500x/47964518.jpg)

... We are well aware of this issue. It will be fixed.

**Comment by israelcoin** [comment]
ok, hopefully this file will resolve the issue.
Guy, please test and update as needed.
https://www.dropbox.com/s/78x5ze8kyw4m1j3/isracoin-qt.icns

**Comment by guysoft** [comment]
Should be able to try out and build tonight

**Comment by guysoft** [comment]
Fixed, Released update 1 for Mac:
https://github.com/israelcoin/Isracoin/releases/tag/v1.6-mac-update-1
