### ISSUE TITLE
Linux compilation is useless - not compiled as static

### ISSUE THREAD

**Issue by shaulliv** [israelcoin/Isracoin#9]
because the wallet was compiled the outdated libminiupnpc.so.8 library systems that installed with version 9 of the library can't run the wallet.

**Comment by guysoft** [comment]
@shaulliv What distro?

**Comment by shaulliv** [comment]
manjaro 0.8.9 Ascella

**Comment by guysoft** [comment]
Ok the linux compilation is not done at all right, changed title of report. @israelcoin You should deal with it.

Should be configured like this:

```
./autogen.sh
./configure LDFLAGS=-static
make
sudo make install
```

With the critical part being `LDFLAGS=-static`

In the meantime @shaulliv I suggest you compile it yourself. If you need help ask here :)

**Comment by guysoft** [comment]
Looks like you can't just compile as static without hitting a lot of symbol errors. Most popular one is:
`(.text+0x11): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version` (after that everything fails).

See no choice other than [setting up a gitian build machine as described here](https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#perform-gitian-builds)

**Comment by guysoft** [comment]
Upcomming 1.6.1 fixes this issue
